### ISSUE TITLE
Add index.html & watch.html & broadcast.html

### ISSUE THREAD

**Issue by Kailang** [rohansub/mixtaped-demo#1]
index.html
- list of current broadcasting hosts

watch.html?${id}
- viewer's page for broadcaster ${id}

broadcast.html
- broadcaster's page

**Comment by Kailang** [comment]
@rohansub I'll also finish the broadcast.html tonight since they are all about the same.
Please add some route to express afterward.

**Comment by rohansub** [comment]
Sounds good to me. I'll try to figure out the routing stuff by Tuesday.

**Comment by Kailang** [comment]
#2
