### ISSUE TITLE
Add routing to server.js

### ISSUE THREAD

**Issue by rohansub** [rohansub/mixtaped-demo#4]
Route server.js to the correct pages and modify watch.html to use url route (instead of parameters).

**Comment by Kailang** [comment]
@rohansub What's iss4 branch? Is it merged already?

**Comment by rohansub** [comment]
@Kailang yeah I merged it to master.

**Comment by Kailang** [comment]
#6 #7 
@rohansub Please, create a pull request and confirm merge in GitHub, or we cannot delete the branch.

**Comment by rohansub** [comment]
@Kailang What do you mean? You already closed the branch. I only see master in the repository.

**Comment by Kailang** [comment]
I mean next time when you are merging the branches to master.
This time I have to 1st merge master to iss4, then merge iss4 to master, and then I can delete the iss4.

**Comment by Kailang** [comment]
https://touhou.live
https://touhou.live/broadcast

Good job!
